Bug 1123527 - Added #error cases for impossible platforms. r=glandium.
cppcheck says:

> b2g/app/nsBrowserApp.cpp:251: error: Uninitialized variable: gotCounters
> browser/app/nsBrowserApp.cpp:637: error: Uninitialized variable: gotCounters

It's a false positive because one of XP_WIN and XP_UNIX is always defined, but
it doesn't hurt to make that fact clearer.